<<<<<<< HEAD
export const ActionTypes={
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
    CART_PRODUCTS:"CART_PRODUCTS",
    DELETE_PRODUCT:"DELETE_PRODUCT",
    EMPTY_CART:"EMPTY_CART"
=======
export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    
>>>>>>> 8000d6aefee7ac732088c8e588acff330cae9e04
}